spring:
  datasource:
    url: jdbc:h2:mem:studytracker;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
